# MySQL 配置
[mysql]
host = localhost
user = root
password = dzlhys
database = edu_database

# Redis 配置
[redis]
host = localhost
port = 6379
password = 1234
db = 0

# Milvus 配置
[milvus]
host = localhost
port = 19530
# 记得创建这个表
database_name = itcast
collection_name = edurag_final

# LLM 配置
[llm]
model = qwen-plus
# dashscope_api_key = ''
dashscope_base_url = https://dashscope.aliyuncs.com/compatible-mode/v1

# 检索参数配置
[retrieval]
parent_chunk_size = 512
child_chunk_size = 128
chunk_overlap = 30
retrieval_k = 5
candidate_m = 2

# 日志配置
[logger]
log_file = logs/app.log
# 应用配置
[app]
valid_sources = ["ai", "java", "test", "ops", "bigdata"]
customer_service_phone = 12345678
